using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class EnemyAI : MonoBehaviour
{
    

    private NavMeshAgent agent;
    [SerializeField] private Transform _location;

    private bool z»pla = false;

    Animator animator;
    private void Start()
    {
        agent = GetComponent<NavMeshAgent>();
        animator = GetComponent<Animator>();
    }

    private void Update()
    {
        agent.SetDestination (_location.transform.position);
        animator.SetBool("isRunning", true);
        if (agent.isOnOffMeshLink)
        {
            var meshlink = agent.currentOffMeshLinkData;

            if (!z»pla && meshlink.offMeshLink.area == NavMesh.GetAreaFromName("Start"))
            {
                JumpAnimation();
                animator.SetBool("Jump",true);
                animator.SetBool("isRunning", false);
                z»pla = true;
            }
        }
        else
        {
            z»pla = false;
        }            
    }

    public void JumpAnimation()
    {
        animator.SetInteger("JumpIndex", Random.Range(0, 3));
        animator.SetTrigger("Jump");
    }
}
